appname = jhboss
httpport = 12306
runmode = dev

sessionon = true

[postgresql]
dbhost = localhost
dbport = 5432
dbuser = postgres
dbpasswd = Kyb^15273031604
dbbase = juhe_pay

[gateway]
host = http://localhost:12309/
